### ISSUE TITLE
Minor Navbar Redesign

### ISSUE THREAD

**Issue by zacktraczyk** [SlugPath/SlugPath#270]
# Scope

Simplify the navbar a bit.

## TODO

- [ ] Update logo
- [ ] Remove Github link
- [ ] Restyle feedback button
- [ ] Update light/dark slider
